#!/bin/bash
#SBATCH -N 1
#SBATCH --tasks-per-node=28
#SBATCH --time=24:00:00
#SBATCH --error="%x.e%j"
#SBATCH --output="%x.o%j"
#SBATCH --job-name="MOR10_ed09"
#SBATCH --mem=120G

module load OpenMPI/3.0.0-GCC-7.2.0-2.29 
module load apps/orca/4.2.0
 
export RSH_COMMAND="/usr/bin/ssh -x"

cd /mnt/storage/scratch/zw18965/TMC34/wB97X-V

echo ${SLURM_NODELIST} > MOR10_ed09.nodes

$(which orca) "MOR10_ed09.in" &> "MOR10_ed09.out"
