#!/bin/bash
#SBATCH -N 1
#SBATCH --tasks-per-node=28
#SBATCH --time=24:00:00
#SBATCH --error="%x.e%j"
#SBATCH --output="%x.o%j"
#SBATCH --job-name="TMD22_CoF"
#SBATCH --mem=120G

module load OpenMPI/3.0.0-GCC-7.2.0-2.29 
module load apps/orca/4.2.0
 
export RSH_COMMAND="/usr/bin/ssh -x"

cd /mnt/storage/scratch/zw18965/TMC34/DSD-BLYP-D3BJ

echo ${SLURM_NODELIST} > TMD22_CoF.nodes

$(which orca) "TMD22_CoF.in" &> "TMD22_CoF.out"
